version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app/:z
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      FALCON_DB: postgres://todoapp@postgres/todos

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos

  phppgadmin:
    # fixed fork of jacksoncage/phppgadmin
    image: dockage/phppgadmin
    ports:
        - "80:80"
    environment:
        - PHP_PG_ADMIN_SERVER_HOST=postgres
        - PHP_PG_ADMIN_SERVER_PORT=5432
        - PHP_PG_ADMIN_SERVER_DEFAULT_DB=todos
    links:
        - postgres:postgres